language: ruby
env:
  - ARUBA_TIMEOUT=240
before_install:
  - gem update --system
  - gem update bundler
  - gem cleanup bundler
cache: bundler
rvm:
  - 2.3.0
  - jruby-19mode
install:
  - "travis_retry bundle install --jobs 8"
gemfile:
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.0.gemfile
matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-19mode
      gemfile: gemfiles/rails5.0.gemfile
    - rvm: 2.1.5
      gemfile: gemfiles/rails5.0.gemfile
